root: true
extends:
- plugin:@mysticatea/es2019
- plugin:@mysticatea/+node

rules:
  no-console: "off"
  no-process-env: "off"
  no-void: "off"
  no-unused-expressions:
  - error
  - allowTaggedTemplates: true

overrides:
- files: ["*.ts"]
  rules:
    no-redeclare: "off"
